//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORES
    {
        public AUTORES()
        {
            this.TRABALHOS = new HashSet<TRABALHOS>();
        }
    
        public int id { get; set; }
        public string nomeAutor { get; set; }
        public string sobrenomeAutor { get; set; }
        public string nomesMeioAutor { get; set; }
    
        public virtual ICollection<TRABALHOS> TRABALHOS { get; set; }
    }
}
