//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORES
    {
        public int id { get; set; }
        public string nomeAutor { get; set; }
        public string sobrenomeAutor { get; set; }
        public string nomesMeioAutor { get; set; }
        public Nullable<int> idTrabalho { get; set; }
    
        public virtual TRABALHOS TRABALHOS { get; set; }
    }
}
