//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADES
    {
        public CIDADES()
        {
            this.ENDERECOS = new HashSet<ENDERECOS>();
        }
    
        public int id { get; set; }
        public string nomeCidade { get; set; }
        public int idEstado { get; set; }
    
        public virtual ICollection<ENDERECOS> ENDERECOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
}
