//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDERECOS
    {
        public ENDERECOS()
        {
            this.CEDENTES = new HashSet<CEDENTES>();
            this.INSCRITOS = new HashSet<INSCRITOS>();
        }
    
        public int id { get; set; }
        public string nomeEndereco { get; set; }
        public string numeroEndereco { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public int idCidade { get; set; }
        public int idLogradouro { get; set; }
        public Nullable<int> idPaises { get; set; }
    
        public virtual ICollection<CEDENTES> CEDENTES { get; set; }
        public virtual CIDADES CIDADES { get; set; }
        public virtual LOGRADOUROS LOGRADOUROS { get; set; }
        public virtual ICollection<INSCRITOS> INSCRITOS { get; set; }
        public virtual PAISES PAISES { get; set; }
    }
}
