//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.CIDADES = new HashSet<CIDADES>();
        }
    
        public int id { get; set; }
        public string nomeEstado { get; set; }
        public string siglaEstado { get; set; }
    
        public virtual ICollection<CIDADES> CIDADES { get; set; }
    }
}
