//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRITOS
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string nacionalidade { get; set; }
        public string email { get; set; }
        public string areaProfissional { get; set; }
        public string infoProfissional { get; set; }
        public string infoAcademica { get; set; }
        public Nullable<bool> palestrante { get; set; }
        public Nullable<int> idTrabalho { get; set; }
        public Nullable<int> idEndereco { get; set; }
        public string rg_rne { get; set; }
        public string situacaoAcademica { get; set; }
    
        public virtual BOLETOS BOLETOS { get; set; }
        public virtual ENDERECOS ENDERECOS { get; set; }
        public virtual TRABALHOS TRABALHOS { get; set; }
    }
}
