//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CEDENTES> CEDENTES { get; set; }
        public DbSet<CIDADES> CIDADES { get; set; }
        public DbSet<CONTAS> CONTAS { get; set; }
        public DbSet<ENDERECOS> ENDERECOS { get; set; }
        public DbSet<ESTADOS> ESTADOS { get; set; }
        public DbSet<LOGRADOUROS> LOGRADOUROS { get; set; }
        public DbSet<VALORES> VALORES { get; set; }
        public DbSet<AUTORES> AUTORES { get; set; }
        public DbSet<TRABALHOS> TRABALHOS { get; set; }
        public DbSet<BOLETOS> BOLETOS { get; set; }
        public DbSet<INSCRITOS> INSCRITOS { get; set; }
        public DbSet<PAISES> PAISES { get; set; }
    }
}
