//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscricaoCongresso.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABALHOS
    {
        public TRABALHOS()
        {
            this.AUTORES = new HashSet<AUTORES>();
            this.INSCRITOS = new HashSet<INSCRITOS>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string resumo { get; set; }
    
        public virtual ICollection<AUTORES> AUTORES { get; set; }
        public virtual ICollection<INSCRITOS> INSCRITOS { get; set; }
    }
}
